
package com.qhjf.cfm.web.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "authorPortType", targetNamespace = "http://com.sinosoft.service.impl/webservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthorPortType {


    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payData", targetNamespace = "http://com.sinosoft.service.impl/webservice", className = "com.qhjf.cfm.web.webservice.client.PayData")
    @ResponseWrapper(localName = "payDataResponse", targetNamespace = "http://com.sinosoft.service.impl/webservice", className = "com.qhjf.cfm.web.webservice.client.PayDataResponse")
    public String payData(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml);

}
