<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sinosoft.service.impl/webservice" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="authorService" targetNamespace="http://com.sinosoft.service.impl/webservice">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://com.sinosoft.service.impl/webservice" elementFormDefault="unqualified" targetNamespace="http://com.sinosoft.service.impl/webservice" version="1.0">

  <xs:element name="payData" type="tns:payData"/>

  <xs:element name="payDataResponse" type="tns:payDataResponse"/>

  <xs:complexType name="payData">
    <xs:sequence>
      <xs:element minOccurs="0" name="xml" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="payDataResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="payDataResponse">
    <wsdl:part element="tns:payDataResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="payData">
    <wsdl:part element="tns:payData" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="authorPortType">
    <wsdl:operation name="payData">
      <wsdl:input message="tns:payData" name="payData">
    </wsdl:input>
      <wsdl:output message="tns:payDataResponse" name="payDataResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="authorServiceSoapBinding" type="tns:authorPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="payData">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="payData">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="payDataResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="authorService">
    <wsdl:port binding="tns:authorServiceSoapBinding" name="authorPortName">
      <soap:address location="http://10.164.26.57:7090/newcomp/ws/author"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>