package com.qhjf.cfm.clients;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-15T23:47:28.376+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "www.seeyon.com", name = "metlifeApplyPayServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface MetlifeApplyPayServicePortType {

    @WebMethod(action = "urn:pushStatus")
    @Action(input = "urn:pushStatus", output = "urn:pushStatusResponse")
    @RequestWrapper(localName = "pushStatus", targetNamespace = "http://metlife.services.v3x.seeyon.com", className = "com.qhjf.cfm.clients.PushStatus")
    @ResponseWrapper(localName = "pushStatusResponse", targetNamespace = "http://metlife.services.v3x.seeyon.com", className = "com.qhjf.cfm.clients.PushStatusResponse")
    @WebResult(name = "return", targetNamespace = "http://metlife.services.v3x.seeyon.com")
    public java.lang.String pushStatus(
        @WebParam(name = "token", targetNamespace = "http://metlife.services.v3x.seeyon.com")
        java.lang.String token,
        @WebParam(name = "xmlString", targetNamespace = "http://metlife.services.v3x.seeyon.com")
        java.lang.String xmlString
    );
}
