
package com.qhjf.cfm.clients;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-15T23:47:28.396+08:00
 * Generated source version: 3.2.6
 *
 */

public class MetlifeApplyPayServicePortType_MetlifeApplyPayServiceHttpEndpoint_Server{

    protected MetlifeApplyPayServicePortType_MetlifeApplyPayServiceHttpEndpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MetlifeApplyPayServiceHttpEndpointImpl();
        String address = "http://10.164.26.25:80/seeyon/services/metlifeApplyPayService.metlifeApplyPayServiceHttpSoap12Endpoint/";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new MetlifeApplyPayServicePortType_MetlifeApplyPayServiceHttpEndpoint_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
