
package com.qhjf.cfm.clients;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-15T23:47:28.203+08:00
 * Generated source version: 3.2.6
 *
 */
public final class MetlifeApplyPayServicePortType_MetlifeApplyPayServiceHttpSoap11Endpoint_Client {

    private static final QName SERVICE_NAME = new QName("www.seeyon.com", "metlifeApplyPayService");

    private MetlifeApplyPayServicePortType_MetlifeApplyPayServiceHttpSoap11Endpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MetlifeApplyPayService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MetlifeApplyPayService ss = new MetlifeApplyPayService(wsdlURL, SERVICE_NAME);
        MetlifeApplyPayServicePortType port = ss.getMetlifeApplyPayServiceHttpSoap11Endpoint();

        {
        System.out.println("Invoking pushStatus...");
        java.lang.String _pushStatus_token = "";
        java.lang.String _pushStatus_xmlString = "";
        java.lang.String _pushStatus__return = port.pushStatus(_pushStatus_token, _pushStatus_xmlString);
        System.out.println("pushStatus.result=" + _pushStatus__return);


        }

        System.exit(0);
    }

}
