
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.qhjf.cfm.clients;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-15T23:47:28.306+08:00
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "metlifeApplyPayService",
                      portName = "metlifeApplyPayServiceHttpSoap11Endpoint",
                      targetNamespace = "www.seeyon.com",
                      wsdlLocation = "file:webservice.wsdl",
                      endpointInterface = "com.qhjf.cfm.clients.MetlifeApplyPayServicePortType")

public class MetlifeApplyPayServiceHttpSoap11EndpointImpl implements MetlifeApplyPayServicePortType {

    private static final Logger LOG = Logger.getLogger(MetlifeApplyPayServiceHttpSoap11EndpointImpl.class.getName());

    /* (non-Javadoc)
     * @see com.qhjf.cfm.clients.MetlifeApplyPayServicePortType#pushStatus(java.lang.String token, java.lang.String xmlString)*
     */
    public java.lang.String pushStatus(java.lang.String token, java.lang.String xmlString) {
        LOG.info("Executing operation pushStatus");
        System.out.println(token);
        System.out.println(xmlString);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
