
package com.qhjf.cfm.web.webservice.oa.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OAServer", targetNamespace = "http://server.oa.webservice.web.cfm.qhjf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OAServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reciveDate", targetNamespace = "http://server.oa.webservice.web.cfm.qhjf.com/", className = "com.qhjf.cfm.web.webservice.oa.server.ReciveDate")
    @ResponseWrapper(localName = "reciveDateResponse", targetNamespace = "http://server.oa.webservice.web.cfm.qhjf.com/", className = "com.qhjf.cfm.web.webservice.oa.server.ReciveDateResponse")
    @Action(input = "http://server.oa.webservice.web.cfm.qhjf.com/OAServer/reciveDateRequest", output = "http://server.oa.webservice.web.cfm.qhjf.com/OAServer/reciveDateResponse")
    public String reciveDate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryStatus", targetNamespace = "http://server.oa.webservice.web.cfm.qhjf.com/", className = "com.qhjf.cfm.web.webservice.oa.server.QueryStatus")
    @ResponseWrapper(localName = "queryStatusResponse", targetNamespace = "http://server.oa.webservice.web.cfm.qhjf.com/", className = "com.qhjf.cfm.web.webservice.oa.server.QueryStatusResponse")
    @Action(input = "http://server.oa.webservice.web.cfm.qhjf.com/OAServer/queryStatusRequest", output = "http://server.oa.webservice.web.cfm.qhjf.com/OAServer/queryStatusResponse")
    public String queryStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
