
package com.seeyon;

import com.seeyon.ctp.services.xsd.UserToken;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "authorityServicePortType", targetNamespace = "www.seeyon.com")
@XmlSeeAlso({
    com.seeyon.ctp.common.authenticate.domain.xsd.ObjectFactory.class,
    com.seeyon.ctp.services.xsd.ObjectFactory.class,
    com.seeyon.v3x.services.impl.ObjectFactory.class,
    com.seeyon.v3x.services.xsd.ObjectFactory.class,
    com.seeyon.util.xsd.ObjectFactory.class
})
public interface AuthorityServicePortType {


    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns com.seeyon.ctp.services.xsd.UserToken
     */
    @WebMethod(action = "urn:getUserToken")
    @WebResult(targetNamespace = "http://impl.services.v3x.seeyon.com")
    @RequestWrapper(localName = "getUserToken", targetNamespace = "http://impl.services.v3x.seeyon.com", className = "com.seeyon.v3x.services.impl.GetUserToken")
    @ResponseWrapper(localName = "getUserTokenResponse", targetNamespace = "http://impl.services.v3x.seeyon.com", className = "com.seeyon.v3x.services.impl.GetUserTokenResponse")
    public UserToken getUserToken(
        @WebParam(name = "userName", targetNamespace = "http://impl.services.v3x.seeyon.com")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://impl.services.v3x.seeyon.com")
        String password);

    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns com.seeyon.ctp.services.xsd.UserToken
     * @throws ServiceException
     */
    @WebMethod(action = "urn:authenticate")
    @WebResult(targetNamespace = "http://impl.services.v3x.seeyon.com")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://impl.services.v3x.seeyon.com", className = "com.seeyon.v3x.services.impl.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://impl.services.v3x.seeyon.com", className = "com.seeyon.v3x.services.impl.AuthenticateResponse")
    public UserToken authenticate(
        @WebParam(name = "userName", targetNamespace = "http://impl.services.v3x.seeyon.com")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://impl.services.v3x.seeyon.com")
        String password)
        throws ServiceException
    ;

}
