
package com.seeyon;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "authorityService", targetNamespace = "www.seeyon.com")
public class AuthorityService
    extends Service
{

    private static URL AUTHORITYSERVICE_WSDL_LOCATION;
    private static WebServiceException AUTHORITYSERVICE_EXCEPTION;
    private final static QName AUTHORITYSERVICE_QNAME = new QName("www.seeyon.com", "authorityService");

    public AuthorityService(String wsdl) throws MalformedURLException{
    	super(new URL(wsdl), AUTHORITYSERVICE_QNAME);
    }

    public AuthorityService() {
        super(__getWsdlLocation(), AUTHORITYSERVICE_QNAME);
    }

    public AuthorityService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHORITYSERVICE_QNAME, features);
    }

    public AuthorityService(URL wsdlLocation) {
        super(wsdlLocation, AUTHORITYSERVICE_QNAME);
    }

    public AuthorityService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHORITYSERVICE_QNAME, features);
    }

    public AuthorityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthorityService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthorityServicePortType
     */
    @WebEndpoint(name = "authorityServiceHttpSoap11Endpoint")
    public AuthorityServicePortType getAuthorityServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("www.seeyon.com", "authorityServiceHttpSoap11Endpoint"), AuthorityServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthorityServicePortType
     */
    @WebEndpoint(name = "authorityServiceHttpSoap11Endpoint")
    public AuthorityServicePortType getAuthorityServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("www.seeyon.com", "authorityServiceHttpSoap11Endpoint"), AuthorityServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHORITYSERVICE_EXCEPTION!= null) {
            throw AUTHORITYSERVICE_EXCEPTION;
        }
        return AUTHORITYSERVICE_WSDL_LOCATION;
    }

}
