
package com.seeyon;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "metlifeApplyPayService", targetNamespace = "www.seeyon.com", wsdlLocation = "http://oa-sit.metlife.com.cn/seeyon/services/metlifeApplyPayService?wsdl")
public class MetlifeApplyPayService
    extends Service
{

    private static URL METLIFEAPPLYPAYSERVICE_WSDL_LOCATION;
    private static WebServiceException METLIFEAPPLYPAYSERVICE_EXCEPTION;
    private final static QName METLIFEAPPLYPAYSERVICE_QNAME = new QName("www.seeyon.com", "metlifeApplyPayService");

    public MetlifeApplyPayService(String wsdl) throws MalformedURLException{
    	super(new URL(wsdl), METLIFEAPPLYPAYSERVICE_QNAME);
    }

    public MetlifeApplyPayService() {
        super(__getWsdlLocation(), METLIFEAPPLYPAYSERVICE_QNAME);
    }

    public MetlifeApplyPayService(WebServiceFeature... features) {
        super(__getWsdlLocation(), METLIFEAPPLYPAYSERVICE_QNAME, features);
    }

    public MetlifeApplyPayService(URL wsdlLocation) {
        super(wsdlLocation, METLIFEAPPLYPAYSERVICE_QNAME);
    }

    public MetlifeApplyPayService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, METLIFEAPPLYPAYSERVICE_QNAME, features);
    }

    public MetlifeApplyPayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MetlifeApplyPayService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MetlifeApplyPayServicePortType
     */
    @WebEndpoint(name = "metlifeApplyPayServiceHttpSoap11Endpoint")
    public MetlifeApplyPayServicePortType getMetlifeApplyPayServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("www.seeyon.com", "metlifeApplyPayServiceHttpSoap11Endpoint"), MetlifeApplyPayServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MetlifeApplyPayServicePortType
     */
    @WebEndpoint(name = "metlifeApplyPayServiceHttpSoap11Endpoint")
    public MetlifeApplyPayServicePortType getMetlifeApplyPayServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("www.seeyon.com", "metlifeApplyPayServiceHttpSoap11Endpoint"), MetlifeApplyPayServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (METLIFEAPPLYPAYSERVICE_EXCEPTION!= null) {
            throw METLIFEAPPLYPAYSERVICE_EXCEPTION;
        }
        return METLIFEAPPLYPAYSERVICE_WSDL_LOCATION;
    }

}
