
package com.seeyon;

import com.seeyon.v3x.services.metlife.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "metlifeApplyPayServicePortType", targetNamespace = "www.seeyon.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MetlifeApplyPayServicePortType {


    /**
     * 
     * @param token
     * @param xmlString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:pushStatus")
    @WebResult(targetNamespace = "http://metlife.services.v3x.seeyon.com")
    @RequestWrapper(localName = "pushStatus", targetNamespace = "http://metlife.services.v3x.seeyon.com", className = "com.seeyon.v3x.services.metlife.PushStatus")
    @ResponseWrapper(localName = "pushStatusResponse", targetNamespace = "http://metlife.services.v3x.seeyon.com", className = "com.seeyon.v3x.services.metlife.PushStatusResponse")
    public String pushStatus(
        @WebParam(name = "token", targetNamespace = "http://metlife.services.v3x.seeyon.com")
        String token,
        @WebParam(name = "xmlString", targetNamespace = "http://metlife.services.v3x.seeyon.com")
        String xmlString);

}
